// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { NotificationServiceTaskManagerTasksTriggerCreatedWebhookWebhookProcedure } from './manager-tasks-trigger-created-webhook-webhook.js';
export { NotificationServiceTaskManagerTasksTriggerUpdatedWebhookWebhookProcedure } from './manager-tasks-trigger-updated-webhook-webhook.js';
export { NotificationServiceNotificationsTriggerSentWebhookProcedure } from './trigger-sent-webhook.js';

import type { Procedure } from "@c4c/core";
import { NotificationServiceTaskManagerTasksTriggerCreatedWebhookWebhookProcedure } from './manager-tasks-trigger-created-webhook-webhook.js';
import { NotificationServiceTaskManagerTasksTriggerUpdatedWebhookWebhookProcedure } from './manager-tasks-trigger-updated-webhook-webhook.js';
import { NotificationServiceNotificationsTriggerSentWebhookProcedure } from './trigger-sent-webhook.js';

export const NotificationServiceTriggers: Procedure[] = [
  NotificationServiceTaskManagerTasksTriggerCreatedWebhookWebhookProcedure,
  NotificationServiceTaskManagerTasksTriggerUpdatedWebhookWebhookProcedure,
  NotificationServiceNotificationsTriggerSentWebhookProcedure
];
