// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { NotificationsTriggerSentProcedure } from './notifications-trigger-sent.gen.js';

import type { Procedure } from "@c4c/core";
import { NotificationsTriggerSentProcedure } from './notifications-trigger-sent.gen.js';

export const NotificationServiceTriggers: Procedure[] = [
  NotificationsTriggerSentProcedure
];
