// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { ManagerTasksTriggerCreatedWebhookProcedure } from './manager-tasks-trigger-created-webhook.js';
export { ManagerTasksTriggerUpdatedWebhookProcedure } from './manager-tasks-trigger-updated-webhook.js';
export { TriggerSentProcedure } from './trigger-sent.js';

import type { Procedure } from "@c4c/core";
import { ManagerTasksTriggerCreatedWebhookProcedure } from './manager-tasks-trigger-created-webhook.js';
import { ManagerTasksTriggerUpdatedWebhookProcedure } from './manager-tasks-trigger-updated-webhook.js';
import { TriggerSentProcedure } from './trigger-sent.js';

export const NotificationServiceTriggers: Procedure[] = [
  ManagerTasksTriggerCreatedWebhookProcedure,
  ManagerTasksTriggerUpdatedWebhookProcedure,
  TriggerSentProcedure
];
