// This file is auto-generated by c4c integrate command
// Do not edit manually.

import type { Procedure, Contract } from "@c4c/core";
import { z } from "zod";

export const ManagerTasksTriggerUpdatedWebhookContract: Contract = {
  name: "notification-service.task.manager.tasks.trigger.updated.webhook",
  description: "Webhook fired when a task is updated",
  input: z.unknown(),
  output: z.record(z.string(), z.unknown()),
  metadata: {
    exposure: "external" as const,
    roles: ["workflow-node"],
    provider: "notification-service",
    operation: "taskManagerTasksTriggerUpdatedWebhook",
    tags: ["notification-service", "webhook"],
    type: "trigger" as const,
    trigger: {
      type: "webhook",
    },
  },
};

// Webhook triggers don't have a handler - they are registered as event receivers
export const ManagerTasksTriggerUpdatedWebhookProcedure: Procedure = {
  contract: ManagerTasksTriggerUpdatedWebhookContract,
  handler: async () => {
    throw new Error('Webhook triggers should not be called directly - they are invoked by the workflow engine');
  },
};
