// This file is auto-generated by c4c integrate command
// Do not edit manually.

import type { Procedure, Contract } from "@c4c/core";
import { z } from "zod";

export const NotificationServiceNotificationsTriggerSentWebhookContract: Contract = {
  name: "notification-service.notifications.trigger.sent.webhook",
  description: "Webhook trigger that fires when a notification is sent",
  input: z.object({
  id: z.string(),
  message: z.string(),
  recipient: z.string().optional(),
  channel: z.enum(["email", "sms", "push", "webhook"]).optional(),
  priority: z.enum(["low", "normal", "high", "urgent"]).optional(),
  status: z.enum(["pending", "sent", "failed"]),
  metadata: z.record(z.unknown()).optional(),
  sentAt: z.string().optional(),
  createdAt: z.string()
}),
  output: z.object({
  success: z.boolean(),
  message: z.string().optional()
}),
  metadata: {
    exposure: "external" as const,
    roles: ["workflow-node"],
    provider: "notification-service",
    operation: "notificationsTriggerSentWebhook",
    tags: ["notification-service", "webhook"],
    type: "trigger" as const,
    trigger: {
      type: "webhook",
    },
  },
};

// Webhook triggers don't have a handler - they are registered as event receivers
export const NotificationServiceNotificationsTriggerSentWebhookProcedure: Procedure = {
  contract: NotificationServiceNotificationsTriggerSentWebhookContract,
  handler: async () => {
    throw new Error('Webhook triggers should not be called directly - they are invoked by the workflow engine');
  },
};
