// This file is auto-generated by c4c integrate command
// Do not edit manually.

import type { Procedure, Contract } from "@c4c/core";
import { z } from "zod";

export const NotificationServiceTaskManagerTasksTriggerCreatedWebhookWebhookContract: Contract = {
  name: "notification-service.task.manager.tasks.trigger.created.webhook.webhook",
  description: "Webhook fired when a new task is created",
  input: z.object({
  success: z.boolean(),
  message: z.string().optional()
}),
  output: z.object({
  success: z.boolean(),
  message: z.string().optional()
}),
  metadata: {
    exposure: "external" as const,
    roles: ["workflow-node"],
    provider: "notification-service",
    operation: "taskManagerTasksTriggerCreatedWebhookWebhook",
    tags: ["notification-service", "webhook"],
    type: "trigger" as const,
    trigger: {
      type: "webhook",
    },
  },
};

// Webhook triggers don't have a handler - they are registered as event receivers
export const NotificationServiceTaskManagerTasksTriggerCreatedWebhookWebhookProcedure: Procedure = {
  contract: NotificationServiceTaskManagerTasksTriggerCreatedWebhookWebhookContract,
  handler: async () => {
    throw new Error('Webhook triggers should not be called directly - they are invoked by the workflow engine');
  },
};
