// This file is auto-generated by c4c integrate command
// Do not edit manually.

import type { Procedure, Contract } from "@c4c/core";
import { z } from "zod";

export const TaskManagerTasksTriggerCreatedContract: Contract = {
  name: "notification-service.task.manager.tasks.trigger.created",
  description: "Triggered when a new task is created",
  input: z.unknown(),
  output: z.record(z.string(), z.unknown()),
  metadata: {
    exposure: "external" as const,
    roles: ["workflow-node"],
    provider: "notification-service",
    operation: "taskManagerTasksTriggerCreated",
    tags: ["notification-service", "webhook"],
    type: "trigger" as const,
    trigger: {
      type: "webhook",
    },
  },
};

// Webhook triggers don't have a handler - they are registered as event receivers
export const TaskManagerTasksTriggerCreatedProcedure: Procedure = {
  contract: TaskManagerTasksTriggerCreatedContract,
  handler: async () => {
    throw new Error('Webhook triggers should not be called directly - they are invoked by the workflow engine');
  },
};
