// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { TaskManagerTasksCreateProcedure } from './tasks-create.gen.js';
export { TaskManagerTasksListRestProcedure } from './tasks-list-rest.gen.js';
export { TaskManagerTasksCreateRestProcedure } from './tasks-create-rest.gen.js';
export { TaskManagerTasksDeleteProcedure } from './tasks-delete.gen.js';
export { TaskManagerTasksDeleteRestProcedure } from './tasks-delete-rest.gen.js';
export { TaskManagerTasksGetRestProcedure } from './tasks-get-rest.gen.js';
export { TaskManagerTasksUpdateRestProcedure } from './tasks-update-rest.gen.js';
export { TaskManagerTasksGetProcedure } from './tasks-get.gen.js';
export { TaskManagerTasksListProcedure } from './tasks-list.gen.js';
export { TaskManagerTasksUpdateProcedure } from './tasks-update.gen.js';

import type { Procedure } from "@c4c/core";
import { TaskManagerTasksCreateProcedure } from './tasks-create.gen.js';
import { TaskManagerTasksListRestProcedure } from './tasks-list-rest.gen.js';
import { TaskManagerTasksCreateRestProcedure } from './tasks-create-rest.gen.js';
import { TaskManagerTasksDeleteProcedure } from './tasks-delete.gen.js';
import { TaskManagerTasksDeleteRestProcedure } from './tasks-delete-rest.gen.js';
import { TaskManagerTasksGetRestProcedure } from './tasks-get-rest.gen.js';
import { TaskManagerTasksUpdateRestProcedure } from './tasks-update-rest.gen.js';
import { TaskManagerTasksGetProcedure } from './tasks-get.gen.js';
import { TaskManagerTasksListProcedure } from './tasks-list.gen.js';
import { TaskManagerTasksUpdateProcedure } from './tasks-update.gen.js';

export const TaskManagerProcedures: Procedure[] = [
  TaskManagerTasksCreateProcedure,
  TaskManagerTasksListRestProcedure,
  TaskManagerTasksCreateRestProcedure,
  TaskManagerTasksDeleteProcedure,
  TaskManagerTasksDeleteRestProcedure,
  TaskManagerTasksGetRestProcedure,
  TaskManagerTasksUpdateRestProcedure,
  TaskManagerTasksGetProcedure,
  TaskManagerTasksListProcedure,
  TaskManagerTasksUpdateProcedure
];

// Re-export triggers
export * from './triggers/index.js';
