// Auto-generated by scripts/generate-contracts.mjs
// Re-exports all generated procedures for registry discovery.
export * from "../contracts/avito/authorization/procedures.gen.js";
export * from "../contracts/avito/items/procedures.gen.js";
export * from "../contracts/avito/messenger/procedures.gen.js";
export * from "../contracts/google/authorization/procedures.gen.js";
export * from "../contracts/google/drive/procedures.gen.js";
export * from "../contracts/google/sheets/procedures.gen.js";
export * from "./math.js";
export * from "./data.js";
