// This file is auto-generated by scripts/generate-contracts.mjs
// Do not edit manually.

import { applyPolicies, type Procedure, type Contract } from "@c4c/core";
import { withOAuth, getOAuthHeaders } from "@c4c/policies";
import * as sdk from "../../../generated/google/sheets/sdk.gen.js";
import * as zod from "../../../generated/google/sheets/zod.gen.js";

export const GoogleSheetsSheetsSpreadsheetsCreateContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.create",
  description: "Creates a spreadsheet, returning the newly created spreadsheet.",
  input: zod.zSheetsSpreadsheetsCreateData,
  output: zod.zSheetsSpreadsheetsCreateResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsCreate",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsCreateHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsCreate(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsCreateProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsCreateContract,
  handler: sheetsSpreadsheetsCreateHandler,
};

export const GoogleSheetsSheetsSpreadsheetsGetContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.get",
  description: "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. By default, data within grids is not returned. You can include grid data in one of 2 ways: * Specify a [field mask](https://developers.google.com/sheets/api/guides/field-masks) listing your desired fields using the `fields` URL parameter in HTTP * Set the includeGridData URL parameter to true. If a field mask is set, the `includeGridData` parameter is ignored For large spreadsheets, as a best practice, retrieve only the specific spreadsheet fields that you want. To retrieve only subsets of spreadsheet data, use the ranges URL parameter. Ranges are specified using [A1 notation](/sheets/api/guides/concepts#cell). You can define a single cell (for example, `A1`) or multiple cells (for example, `A1:D5`). You can also get cells from other sheets within the same spreadsheet (for example, `Sheet2!A1:C4`) or retrieve multiple ranges at once (for example, `?ranges=A1:D5&ranges=Sheet2!A1:C4`). Limiting the range returns only the portions of the spreadsheet that intersect the requested ranges.",
  input: zod.zSheetsSpreadsheetsGetData,
  output: zod.zSheetsSpreadsheetsGetResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsGet",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsGetHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsGet(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsGetProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsGetContract,
  handler: sheetsSpreadsheetsGetHandler,
};

export const GoogleSheetsSheetsSpreadsheec4celoperMetadataGetContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.developer.metadata.get",
  description: "Returns the developer metadata with the specified ID. The caller must specify the spreadsheet ID and the developer metadata's unique metadataId.",
  input: zod.zSheetsSpreadsheec4celoperMetadataGetData,
  output: zod.zSheetsSpreadsheec4celoperMetadataGetResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheec4celoperMetadataGet",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheec4celoperMetadataGetHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheec4celoperMetadataGet(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheec4celoperMetadataGetProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheec4celoperMetadataGetContract,
  handler: sheetsSpreadsheec4celoperMetadataGetHandler,
};

export const GoogleSheetsSheetsSpreadsheec4celoperMetadataSearchContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.developer.metadata.search",
  description: "Returns all developer metadata matching the specified DataFilter. If the provided DataFilter represents a DeveloperMetadataLookup object, this will return all DeveloperMetadata entries selected by it. If the DataFilter represents a location in a spreadsheet, this will return all developer metadata associated with locations intersecting that region.",
  input: zod.zSheetsSpreadsheec4celoperMetadataSearchData,
  output: zod.zSheetsSpreadsheec4celoperMetadataSearchResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheec4celoperMetadataSearch",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheec4celoperMetadataSearchHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheec4celoperMetadataSearch(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheec4celoperMetadataSearchProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheec4celoperMetadataSearchContract,
  handler: sheetsSpreadsheec4celoperMetadataSearchHandler,
};

export const GoogleSheetsSheetsSpreadsheetsSheetsCopyToContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.sheets.copy.to",
  description: "Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet.",
  input: zod.zSheetsSpreadsheetsSheetsCopyToData,
  output: zod.zSheetsSpreadsheetsSheetsCopyToResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsSheetsCopyTo",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsSheetsCopyToHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsSheetsCopyTo(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsSheetsCopyToProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsSheetsCopyToContract,
  handler: sheetsSpreadsheetsSheetsCopyToHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesGetContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.get",
  description: "Returns a range of values from a spreadsheet. The caller must specify the spreadsheet ID and a range.",
  input: zod.zSheetsSpreadsheetsValuesGetData,
  output: zod.zSheetsSpreadsheetsValuesGetResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesGet",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesGetHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesGet(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesGetProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesGetContract,
  handler: sheetsSpreadsheetsValuesGetHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesUpdateContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.update",
  description: "Sets values in a range of a spreadsheet. The caller must specify the spreadsheet ID, range, and a valueInputOption.",
  input: zod.zSheetsSpreadsheetsValuesUpdateData,
  output: zod.zSheetsSpreadsheetsValuesUpdateResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesUpdate",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesUpdateHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesUpdate(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesUpdateProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesUpdateContract,
  handler: sheetsSpreadsheetsValuesUpdateHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesAppendContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.append",
  description: "Appends values to a spreadsheet. The input range is used to search for existing data and find a \"table\" within that range. Values will be appended to the next row of the table, starting with the first column of the table. See the [guide](/sheets/api/guides/values#appending_values) and [sample code](/sheets/api/samples/writing#append_values) for specific details of how tables are detected and data is appended. The caller must specify the spreadsheet ID, range, and a valueInputOption. The `valueInputOption` only controls how the input data will be added to the sheet (column-wise or row-wise), it does not influence what cell the data starts being written to.",
  input: zod.zSheetsSpreadsheetsValuesAppendData,
  output: zod.zSheetsSpreadsheetsValuesAppendResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesAppend",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesAppendHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesAppend(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesAppendProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesAppendContract,
  handler: sheetsSpreadsheetsValuesAppendHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesClearContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.clear",
  description: "Clears values from a spreadsheet. The caller must specify the spreadsheet ID and range. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
  input: zod.zSheetsSpreadsheetsValuesClearData,
  output: zod.zSheetsSpreadsheetsValuesClearResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesClear",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesClearHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesClear(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesClearProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesClearContract,
  handler: sheetsSpreadsheetsValuesClearHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesBatchClearContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.batch.clear",
  description: "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges. Only values are cleared -- all other properties of the cell (such as formatting and data validation) are kept.",
  input: zod.zSheetsSpreadsheetsValuesBatchClearData,
  output: zod.zSheetsSpreadsheetsValuesBatchClearResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesBatchClear",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesBatchClearHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesBatchClear(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesBatchClearProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesBatchClearContract,
  handler: sheetsSpreadsheetsValuesBatchClearHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesBatchClearByDataFilterContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.batch.clear.by.data.filter",
  description: "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more DataFilters. Ranges matching any of the specified data filters will be cleared. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
  input: zod.zSheetsSpreadsheetsValuesBatchClearByDataFilterData,
  output: zod.zSheetsSpreadsheetsValuesBatchClearByDataFilterResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesBatchClearByDataFilter",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesBatchClearByDataFilterHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesBatchClearByDataFilter(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesBatchClearByDataFilterProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesBatchClearByDataFilterContract,
  handler: sheetsSpreadsheetsValuesBatchClearByDataFilterHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesBatchGetContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.batch.get",
  description: "Returns one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges.",
  input: zod.zSheetsSpreadsheetsValuesBatchGetData,
  output: zod.zSheetsSpreadsheetsValuesBatchGetResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesBatchGet",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesBatchGetHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesBatchGet(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesBatchGetProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesBatchGetContract,
  handler: sheetsSpreadsheetsValuesBatchGetHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesBatchGetByDataFilterContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.batch.get.by.data.filter",
  description: "Returns one or more ranges of values that match the specified data filters. The caller must specify the spreadsheet ID and one or more DataFilters. Ranges that match any of the data filters in the request will be returned.",
  input: zod.zSheetsSpreadsheetsValuesBatchGetByDataFilterData,
  output: zod.zSheetsSpreadsheetsValuesBatchGetByDataFilterResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesBatchGetByDataFilter",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesBatchGetByDataFilterHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesBatchGetByDataFilter(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesBatchGetByDataFilterProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesBatchGetByDataFilterContract,
  handler: sheetsSpreadsheetsValuesBatchGetByDataFilterHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.batch.update",
  description: "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more ValueRanges.",
  input: zod.zSheetsSpreadsheetsValuesBatchUpdateData,
  output: zod.zSheetsSpreadsheetsValuesBatchUpdateResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesBatchUpdate",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesBatchUpdateHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesBatchUpdate(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateContract,
  handler: sheetsSpreadsheetsValuesBatchUpdateHandler,
};

export const GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateByDataFilterContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.values.batch.update.by.data.filter",
  description: "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more DataFilterValueRanges.",
  input: zod.zSheetsSpreadsheetsValuesBatchUpdateByDataFilterData,
  output: zod.zSheetsSpreadsheetsValuesBatchUpdateByDataFilterResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsValuesBatchUpdateByDataFilter",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsValuesBatchUpdateByDataFilterHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsValuesBatchUpdateByDataFilter(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateByDataFilterProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateByDataFilterContract,
  handler: sheetsSpreadsheetsValuesBatchUpdateByDataFilterHandler,
};

export const GoogleSheetsSheetsSpreadsheetsBatchUpdateContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.batch.update",
  description: "Applies one or more updates to the spreadsheet. Each request is validated before being applied. If any request is not valid then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. The replies will mirror the requests. For example, if you applied 4 updates and the 3rd one had a reply, then the response will have 2 empty replies, the actual reply, and another empty reply, in that order. Due to the collaborative nature of spreadsheets, it is not guaranteed that the spreadsheet will reflect exactly your changes after this completes, however it is guaranteed that the updates in the request will be applied together atomically. Your changes may be altered with respect to collaborator changes. If there are no collaborators, the spreadsheet should reflect your changes.",
  input: zod.zSheetsSpreadsheetsBatchUpdateData,
  output: zod.zSheetsSpreadsheetsBatchUpdateResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsBatchUpdate",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsBatchUpdateHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsBatchUpdate(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsBatchUpdateProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsBatchUpdateContract,
  handler: sheetsSpreadsheetsBatchUpdateHandler,
};

export const GoogleSheetsSheetsSpreadsheetsGetByDataFilterContract: Contract = {
  name: "googleSheets.sheets.spreadsheets.get.by.data.filter",
  description: "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. This method differs from GetSpreadsheet in that it allows selecting which subsets of spreadsheet data to return by specifying a dataFilters parameter. Multiple DataFilters can be specified. Specifying one or more data filters returns the portions of the spreadsheet that intersect ranges matched by any of the filters. By default, data within grids is not returned. You can include grid data one of 2 ways: * Specify a [field mask](https://developers.google.com/sheets/api/guides/field-masks) listing your desired fields using the `fields` URL parameter in HTTP * Set the includeGridData parameter to true. If a field mask is set, the `includeGridData` parameter is ignored For large spreadsheets, as a best practice, retrieve only the specific spreadsheet fields that you want.",
  input: zod.zSheetsSpreadsheetsGetByDataFilterData,
  output: zod.zSheetsSpreadsheetsGetByDataFilterResponse,
  metadata: {
    exposure: "internal",
    roles: ["workflow-node"],
    provider: "googleSheets",
    operation: "sheetsSpreadsheetsGetByDataFilter",
    tags: ["google", "sheets"],
  },
};

const sheetsSpreadsheetsGetByDataFilterHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "googleSheets");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.sheetsSpreadsheetsGetByDataFilter(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "googleSheets",
    metadataTokenKey: "googleSheetsToken",
    envVar: "GOOGLE_SHEETS_TOKEN",
  })
);

export const GoogleSheetsSheetsSpreadsheetsGetByDataFilterProcedure: Procedure = {
  contract: GoogleSheetsSheetsSpreadsheetsGetByDataFilterContract,
  handler: sheetsSpreadsheetsGetByDataFilterHandler,
};

export const GoogleSheetsProcedures: Procedure[] = [
  GoogleSheetsSheetsSpreadsheetsCreateProcedure,
  GoogleSheetsSheetsSpreadsheetsGetProcedure,
  GoogleSheetsSheetsSpreadsheec4celoperMetadataGetProcedure,
  GoogleSheetsSheetsSpreadsheec4celoperMetadataSearchProcedure,
  GoogleSheetsSheetsSpreadsheetsSheetsCopyToProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesGetProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesUpdateProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesAppendProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesClearProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesBatchClearProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesBatchClearByDataFilterProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesBatchGetProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesBatchGetByDataFilterProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateProcedure,
  GoogleSheetsSheetsSpreadsheetsValuesBatchUpdateByDataFilterProcedure,
  GoogleSheetsSheetsSpreadsheetsBatchUpdateProcedure,
  GoogleSheetsSheetsSpreadsheetsGetByDataFilterProcedure
];
