// Auto-generated by scripts/generate-contracts.mjs
// Re-exports all generated procedures for registry discovery.
export * from "../avito/authorization/procedures.gen.js";
export * from "../avito/items/procedures.gen.js";
export * from "../avito/messenger/procedures.gen.js";
export * from "../google/authorization/procedures.gen.js";
export * from "../google/drive/procedures.gen.js";
export * from "../google/sheets/procedures.gen.js";
