// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { NotificationServiceTaskManagerTasksCreateProcedure } from './task-manager-tasks-create.gen.js';
export { NotificationServiceTaskManagerTasksCreateRestProcedure } from './task-manager-tasks-create-rest.gen.js';
export { NotificationServiceTaskManagerTasksDeleteProcedure } from './task-manager-tasks-delete.gen.js';
export { NotificationServiceTaskManagerTasksDeleteRestProcedure } from './task-manager-tasks-delete-rest.gen.js';
export { NotificationServiceTaskManagerTasksGetProcedure } from './task-manager-tasks-get.gen.js';
export { NotificationServiceTaskManagerTasksGetRestProcedure } from './task-manager-tasks-get-rest.gen.js';
export { NotificationServiceTaskManagerTasksListProcedure } from './task-manager-tasks-list.gen.js';
export { NotificationServiceTaskManagerTasksListRestProcedure } from './task-manager-tasks-list-rest.gen.js';
export { NotificationServiceTaskManagerTasksUpdateProcedure } from './task-manager-tasks-update.gen.js';
export { NotificationServiceTaskManagerTasksUpdateRestProcedure } from './task-manager-tasks-update-rest.gen.js';
export { NotificationServiceNotificationsListProcedure } from './notifications-list.gen.js';
export { NotificationServiceNotificationsListRestProcedure } from './notifications-list-rest.gen.js';
export { NotificationServiceNotificationsSendProcedure } from './notifications-send.gen.js';
export { NotificationServiceNotificationsSubscribeProcedure } from './notifications-subscribe.gen.js';

import type { Procedure } from "@c4c/core";
import { NotificationServiceTaskManagerTasksCreateProcedure } from './task-manager-tasks-create.gen.js';
import { NotificationServiceTaskManagerTasksCreateRestProcedure } from './task-manager-tasks-create-rest.gen.js';
import { NotificationServiceTaskManagerTasksDeleteProcedure } from './task-manager-tasks-delete.gen.js';
import { NotificationServiceTaskManagerTasksDeleteRestProcedure } from './task-manager-tasks-delete-rest.gen.js';
import { NotificationServiceTaskManagerTasksGetProcedure } from './task-manager-tasks-get.gen.js';
import { NotificationServiceTaskManagerTasksGetRestProcedure } from './task-manager-tasks-get-rest.gen.js';
import { NotificationServiceTaskManagerTasksListProcedure } from './task-manager-tasks-list.gen.js';
import { NotificationServiceTaskManagerTasksListRestProcedure } from './task-manager-tasks-list-rest.gen.js';
import { NotificationServiceTaskManagerTasksUpdateProcedure } from './task-manager-tasks-update.gen.js';
import { NotificationServiceTaskManagerTasksUpdateRestProcedure } from './task-manager-tasks-update-rest.gen.js';
import { NotificationServiceNotificationsListProcedure } from './notifications-list.gen.js';
import { NotificationServiceNotificationsListRestProcedure } from './notifications-list-rest.gen.js';
import { NotificationServiceNotificationsSendProcedure } from './notifications-send.gen.js';
import { NotificationServiceNotificationsSubscribeProcedure } from './notifications-subscribe.gen.js';

export const NotificationServiceProcedures: Procedure[] = [
  NotificationServiceTaskManagerTasksCreateProcedure,
  NotificationServiceTaskManagerTasksCreateRestProcedure,
  NotificationServiceTaskManagerTasksDeleteProcedure,
  NotificationServiceTaskManagerTasksDeleteRestProcedure,
  NotificationServiceTaskManagerTasksGetProcedure,
  NotificationServiceTaskManagerTasksGetRestProcedure,
  NotificationServiceTaskManagerTasksListProcedure,
  NotificationServiceTaskManagerTasksListRestProcedure,
  NotificationServiceTaskManagerTasksUpdateProcedure,
  NotificationServiceTaskManagerTasksUpdateRestProcedure,
  NotificationServiceNotificationsListProcedure,
  NotificationServiceNotificationsListRestProcedure,
  NotificationServiceNotificationsSendProcedure,
  NotificationServiceNotificationsSubscribeProcedure
];
