// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { CreateProcedure } from './create.js';
export { ListRestProcedure } from './list-rest.js';
export { CreateRestProcedure } from './create-rest.js';
export { DeleteProcedure } from './delete.js';
export { DeleteRestProcedure } from './delete-rest.js';
export { GetRestProcedure } from './get-rest.js';
export { UpdateRestProcedure } from './update-rest.js';
export { GetProcedure } from './get.js';
export { ListProcedure } from './list.js';
export { UpdateProcedure } from './update.js';

import type { Procedure } from "@c4c/core";
import { CreateProcedure } from './create.js';
import { ListRestProcedure } from './list-rest.js';
import { CreateRestProcedure } from './create-rest.js';
import { DeleteProcedure } from './delete.js';
import { DeleteRestProcedure } from './delete-rest.js';
import { GetRestProcedure } from './get-rest.js';
import { UpdateRestProcedure } from './update-rest.js';
import { GetProcedure } from './get.js';
import { ListProcedure } from './list.js';
import { UpdateProcedure } from './update.js';

export const TaskManagerProcedures: Procedure[] = [
  CreateProcedure,
  ListRestProcedure,
  CreateRestProcedure,
  DeleteProcedure,
  DeleteRestProcedure,
  GetRestProcedure,
  UpdateRestProcedure,
  GetProcedure,
  ListProcedure,
  UpdateProcedure
];

// Re-export triggers
export * from './triggers/index.js';
