// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { TasksCreateProcedure } from './tasks-create.gen.js';
export { TasksListRestProcedure } from './tasks-list-rest.gen.js';
export { TasksCreateRestProcedure } from './tasks-create-rest.gen.js';
export { TasksDeleteProcedure } from './tasks-delete.gen.js';
export { TasksDeleteRestProcedure } from './tasks-delete-rest.gen.js';
export { TasksGetRestProcedure } from './tasks-get-rest.gen.js';
export { TasksUpdateRestProcedure } from './tasks-update-rest.gen.js';
export { TasksGetProcedure } from './tasks-get.gen.js';
export { TasksListProcedure } from './tasks-list.gen.js';
export { TasksUpdateProcedure } from './tasks-update.gen.js';

import type { Procedure } from "@c4c/core";
import { TasksCreateProcedure } from './tasks-create.gen.js';
import { TasksListRestProcedure } from './tasks-list-rest.gen.js';
import { TasksCreateRestProcedure } from './tasks-create-rest.gen.js';
import { TasksDeleteProcedure } from './tasks-delete.gen.js';
import { TasksDeleteRestProcedure } from './tasks-delete-rest.gen.js';
import { TasksGetRestProcedure } from './tasks-get-rest.gen.js';
import { TasksUpdateRestProcedure } from './tasks-update-rest.gen.js';
import { TasksGetProcedure } from './tasks-get.gen.js';
import { TasksListProcedure } from './tasks-list.gen.js';
import { TasksUpdateProcedure } from './tasks-update.gen.js';

export const TaskManagerProcedures: Procedure[] = [
  TasksCreateProcedure,
  TasksListRestProcedure,
  TasksCreateRestProcedure,
  TasksDeleteProcedure,
  TasksDeleteRestProcedure,
  TasksGetRestProcedure,
  TasksUpdateRestProcedure,
  TasksGetProcedure,
  TasksListProcedure,
  TasksUpdateProcedure
];

// Re-export triggers
export * from './triggers/index.js';
