// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { TaskManagerTasksCreateProcedure } from './create.js';
export { TaskManagerTasksListRestProcedure } from './list-rest.js';
export { TaskManagerTasksCreateRestProcedure } from './create-rest.js';
export { TaskManagerTasksDeleteProcedure } from './delete.js';
export { TaskManagerTasksDeleteRestProcedure } from './delete-rest.js';
export { TaskManagerTasksGetRestProcedure } from './get-rest.js';
export { TaskManagerTasksUpdateRestProcedure } from './update-rest.js';
export { TaskManagerTasksGetProcedure } from './get.js';
export { TaskManagerTasksListProcedure } from './list.js';
export { TaskManagerTasksUpdateProcedure } from './update.js';

import type { Procedure } from "@c4c/core";
import { TaskManagerTasksCreateProcedure } from './create.js';
import { TaskManagerTasksListRestProcedure } from './list-rest.js';
import { TaskManagerTasksCreateRestProcedure } from './create-rest.js';
import { TaskManagerTasksDeleteProcedure } from './delete.js';
import { TaskManagerTasksDeleteRestProcedure } from './delete-rest.js';
import { TaskManagerTasksGetRestProcedure } from './get-rest.js';
import { TaskManagerTasksUpdateRestProcedure } from './update-rest.js';
import { TaskManagerTasksGetProcedure } from './get.js';
import { TaskManagerTasksListProcedure } from './list.js';
import { TaskManagerTasksUpdateProcedure } from './update.js';

export const TaskManagerProcedures: Procedure[] = [
  TaskManagerTasksCreateProcedure,
  TaskManagerTasksListRestProcedure,
  TaskManagerTasksCreateRestProcedure,
  TaskManagerTasksDeleteProcedure,
  TaskManagerTasksDeleteRestProcedure,
  TaskManagerTasksGetRestProcedure,
  TaskManagerTasksUpdateRestProcedure,
  TaskManagerTasksGetProcedure,
  TaskManagerTasksListProcedure,
  TaskManagerTasksUpdateProcedure
];

// Re-export triggers
export * from './triggers/index.js';
