// This file is auto-generated by c4c integrate command
// Do not edit manually.

import { applyPolicies, type Procedure, type Contract } from "@c4c/core";
import { withOAuth, getOAuthHeaders } from "@c4c/policies";
import * as sdk from "../../../../generated/task-manager/sdk.gen.js";
import { z } from "zod";

export const TaskManagerNotificationServiceNotificationsSubscribeContract: Contract = {
  name: "task-manager.notification.service.notifications.subscribe",
  description: "Subscribe to notifications on a topic",
  input: z.any(),
  output: z.any(),
  metadata: {
    exposure: "external" as const,
    roles: ["api-endpoint", "workflow-node"],
    provider: "task-manager",
    operation: "notificationServiceNotificationsSubscribe",
    tags: ["task-manager"],
  },
};

const notificationServiceNotificationsSubscribeHandler = applyPolicies(
  async (input, context) => {
    const headers = getOAuthHeaders(context, "task-manager");
    const request: Record<string, unknown> = { ...input };
    if (headers) {
      request.headers = {
        ...((request.headers as Record<string, string> | undefined) ?? {}),
        ...headers,
      };
    }
    const result = await sdk.notificationServiceNotificationsSubscribe(request as any);
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "task-manager",
    metadataTokenKey: "task-managerToken",
    envVar: "TASK_MANAGER_TOKEN",
  })
);

export const TaskManagerNotificationServiceNotificationsSubscribeProcedure: Procedure = {
  contract: TaskManagerNotificationServiceNotificationsSubscribeContract,
  handler: notificationServiceNotificationsSubscribeHandler,
};
