// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { NotificationServiceNotificationsTriggerSentWebhookProcedure } from './notifications-trigger-sent-webhook.gen.js';

import type { Procedure } from "@c4c/core";
import { NotificationServiceNotificationsTriggerSentWebhookProcedure } from './notifications-trigger-sent-webhook.gen.js';

export const NotificationServiceTriggers: Procedure[] = [
  NotificationServiceNotificationsTriggerSentWebhookProcedure
];
