// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { TaskManagerTasksCreateProcedure } from './task-manager-tasks-create.gen.js';
export { TaskManagerTasksCreateRestProcedure } from './task-manager-tasks-create-rest.gen.js';
export { TaskManagerTasksDeleteProcedure } from './task-manager-tasks-delete.gen.js';
export { TaskManagerTasksDeleteRestProcedure } from './task-manager-tasks-delete-rest.gen.js';
export { TaskManagerTasksGetProcedure } from './task-manager-tasks-get.gen.js';
export { TaskManagerTasksGetRestProcedure } from './task-manager-tasks-get-rest.gen.js';
export { TaskManagerTasksListProcedure } from './task-manager-tasks-list.gen.js';
export { TaskManagerTasksListRestProcedure } from './task-manager-tasks-list-rest.gen.js';
export { TaskManagerTasksUpdateProcedure } from './task-manager-tasks-update.gen.js';
export { TaskManagerTasksUpdateRestProcedure } from './task-manager-tasks-update-rest.gen.js';
export { NotificationsListProcedure } from './notifications-list.gen.js';
export { NotificationsListRestProcedure } from './notifications-list-rest.gen.js';
export { NotificationsSendProcedure } from './notifications-send.gen.js';
export { NotificationsSubscribeProcedure } from './notifications-subscribe.gen.js';

import type { Procedure } from "@c4c/core";
import { TaskManagerTasksCreateProcedure } from './task-manager-tasks-create.gen.js';
import { TaskManagerTasksCreateRestProcedure } from './task-manager-tasks-create-rest.gen.js';
import { TaskManagerTasksDeleteProcedure } from './task-manager-tasks-delete.gen.js';
import { TaskManagerTasksDeleteRestProcedure } from './task-manager-tasks-delete-rest.gen.js';
import { TaskManagerTasksGetProcedure } from './task-manager-tasks-get.gen.js';
import { TaskManagerTasksGetRestProcedure } from './task-manager-tasks-get-rest.gen.js';
import { TaskManagerTasksListProcedure } from './task-manager-tasks-list.gen.js';
import { TaskManagerTasksListRestProcedure } from './task-manager-tasks-list-rest.gen.js';
import { TaskManagerTasksUpdateProcedure } from './task-manager-tasks-update.gen.js';
import { TaskManagerTasksUpdateRestProcedure } from './task-manager-tasks-update-rest.gen.js';
import { NotificationsListProcedure } from './notifications-list.gen.js';
import { NotificationsListRestProcedure } from './notifications-list-rest.gen.js';
import { NotificationsSendProcedure } from './notifications-send.gen.js';
import { NotificationsSubscribeProcedure } from './notifications-subscribe.gen.js';

export const NotificationServiceProcedures: Procedure[] = [
  TaskManagerTasksCreateProcedure,
  TaskManagerTasksCreateRestProcedure,
  TaskManagerTasksDeleteProcedure,
  TaskManagerTasksDeleteRestProcedure,
  TaskManagerTasksGetProcedure,
  TaskManagerTasksGetRestProcedure,
  TaskManagerTasksListProcedure,
  TaskManagerTasksListRestProcedure,
  TaskManagerTasksUpdateProcedure,
  TaskManagerTasksUpdateRestProcedure,
  NotificationsListProcedure,
  NotificationsListRestProcedure,
  NotificationsSendProcedure,
  NotificationsSubscribeProcedure
];

// Re-export triggers
export * from './triggers/index.js';
