// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { NotificationServiceNotificationsListProcedure } from './list.js';
export { NotificationServiceNotificationsListRestProcedure } from './list-rest.js';
export { NotificationServiceNotificationsSendProcedure } from './send.js';
export { NotificationServiceNotificationsSubscribeProcedure } from './subscribe.js';

import type { Procedure } from "@c4c/core";
import { NotificationServiceNotificationsListProcedure } from './list.js';
import { NotificationServiceNotificationsListRestProcedure } from './list-rest.js';
import { NotificationServiceNotificationsSendProcedure } from './send.js';
import { NotificationServiceNotificationsSubscribeProcedure } from './subscribe.js';

export const NotificationServiceProcedures: Procedure[] = [
  NotificationServiceNotificationsListProcedure,
  NotificationServiceNotificationsListRestProcedure,
  NotificationServiceNotificationsSendProcedure,
  NotificationServiceNotificationsSubscribeProcedure
];

// Re-export triggers
export * from './triggers/index.js';
