// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { ListProcedure } from './list.js';
export { ListRestProcedure } from './list-rest.js';
export { SendProcedure } from './send.js';
export { SubscribeProcedure } from './subscribe.js';

import type { Procedure } from "@c4c/core";
import { ListProcedure } from './list.js';
import { ListRestProcedure } from './list-rest.js';
import { SendProcedure } from './send.js';
import { SubscribeProcedure } from './subscribe.js';

export const NotificationServiceProcedures: Procedure[] = [
  ListProcedure,
  ListRestProcedure,
  SendProcedure,
  SubscribeProcedure
];

// Re-export triggers
export * from './triggers/index.js';
