// This file is auto-generated by c4c integrate command
// Do not edit manually.

import { applyPolicies, type Procedure, type Contract } from "@c4c/core";
import { withOAuth, getOAuthHeaders } from "@c4c/policies";
import * as sdk from "../../../generated/notification-service/sdk.gen.js";
import { createClient, createConfig } from "@hey-api/client-fetch";
import { z } from "zod";

export const NotificationServiceNotificationsSubscribeContract: Contract = {
  name: "notification-service.notifications.subscribe",
  description: "Subscribe to notifications on a topic",
  input: z.object({
  topic: z.string(),
  webhookUrl: z.string().url()
}),
  output: z.object({
  success: z.boolean(),
  subscriptionId: z.string(),
  topic: z.string()
}),
  metadata: {
    exposure: "external" as const,
    roles: ["api-endpoint", "workflow-node"],
    provider: "notification-service",
    operation: "notificationsSubscribe",
    tags: ["notification-service"],
  },
};

const notificationsSubscribeHandler = applyPolicies(
  async (input, context) => {
    const baseUrl = process.env.NOTIFICATION_SERVICE_URL || context.metadata?.['notification-serviceUrl'] as string | undefined;
    if (!baseUrl) {
      throw new Error(`NOTIFICATION_SERVICE_URL environment variable is not set`);
    }
    
    const headers = getOAuthHeaders(context, "notification-service");
    
    // Create custom client with proper baseURL configuration
    const customClient = createClient(createConfig({ baseUrl }));
    
    const result = await sdk.notificationsSubscribe({ 
      body: input,
      headers,
      client: customClient 
    } as any);
    
    if (result && typeof result === "object" && "data" in result) {
      return (result as { data: unknown }).data;
    }
    return result as unknown;
  },
  withOAuth({
    provider: "notification-service",
    metadataTokenKey: "notification-serviceToken",
    envVar: "NOTIFICATION_SERVICE_TOKEN",
  })
);

export const NotificationServiceNotificationsSubscribeProcedure: Procedure = {
  contract: NotificationServiceNotificationsSubscribeContract,
  handler: notificationsSubscribeHandler,
};
