/**
 * Workflow DevKit HTTP server
 *
 * Creates a Node.js HTTP server that serves the three
 * .well-known/workflow/v1/ endpoints (flow, step, webhook)
 * generated by `workflow build`.
 *
 * Usage:
 *   import { createWorkflowServer } from "@c4c/adapters";
 *   const server = await createWorkflowServer({ port: 3000 });
 */

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createRequire } from "node:module";
import { join } from "node:path";
import { existsSync } from "node:fs";

export interface WorkflowServerOptions {
	/** Port to listen on (default: 3000, or PORT env var) */
	port?: number;
	/** Path to the directory containing .well-known/workflow/v1/ (default: cwd) */
	rootDir?: string;
	/** Pre-loaded handlers (if you want to load them yourself) */
	handlers?: {
		flow: { POST: (req: Request) => Response | Promise<Response> };
		step: { POST: (req: Request) => Response | Promise<Response> };
		webhook: { POST: (req: Request) => Response | Promise<Response> };
	};
}

/**
 * Create and start a workflow HTTP server.
 *
 * Automatically loads the generated handler bundles from
 * .well-known/workflow/v1/ and serves them as HTTP endpoints.
 *
 * Also initializes @workflow/world-local for development storage.
 */
export async function createWorkflowServer(options: WorkflowServerOptions = {}) {
	const port = options.port ?? Number(process.env.PORT) ?? 3000;
	const rootDir = options.rootDir ?? process.cwd();

	let handlers = options.handlers;

	if (!handlers) {
		const wellKnown = join(rootDir, ".well-known", "workflow", "v1");

		// Try ESM wrappers first (.mjs), fall back to CJS (.cjs / .js)
		const flowPath = findHandler(wellKnown, "flow");
		const stepPath = findHandler(wellKnown, "step");
		const webhookPath = findHandler(wellKnown, "webhook");

		if (!flowPath || !stepPath || !webhookPath) {
			throw new Error(
				`Missing workflow handlers in ${wellKnown}. Run \`npx workflow build\` first.`,
			);
		}

		const [flow, step, webhook] = await Promise.all([
			loadHandler(flowPath),
			loadHandler(stepPath),
			loadHandler(webhookPath),
		]);

		handlers = { flow, step, webhook };
	}

	const { flow, step, webhook } = handlers;

	const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
		const url = new URL(req.url || "/", `http://localhost:${port}`);
		const method = req.method || "GET";

		// Read body
		let body = "";
		for await (const chunk of req) body += chunk;

		const headers = new Headers();
		for (const [k, v] of Object.entries(req.headers)) {
			if (v) headers.set(k, Array.isArray(v) ? v[0] : v);
		}

		const init: RequestInit = { method, headers };
		if (method !== "GET" && method !== "HEAD" && body) init.body = body;
		const request = new Request(url.toString(), init);

		try {
			let response: Response;

			if (url.pathname === "/.well-known/workflow/v1/flow" && method === "POST") {
				response = await flow.POST(request);
			} else if (url.pathname === "/.well-known/workflow/v1/step" && method === "POST") {
				response = await step.POST(request);
			} else if (url.pathname.startsWith("/.well-known/workflow/v1/webhook/")) {
				response = await webhook.POST(request);
			} else if (url.pathname === "/health") {
				response = Response.json({ ok: true, timestamp: new Date().toISOString() });
			} else {
				response = new Response("Not Found", { status: 404 });
			}

			res.writeHead(response.status, Object.fromEntries(response.headers));
			res.end(Buffer.from(await response.arrayBuffer()));
		} catch (error) {
			console.error("[c4c] Server error:", error);
			res.writeHead(500, { "Content-Type": "application/json" });
			res.end(JSON.stringify({ error: error instanceof Error ? error.message : String(error) }));
		}
	});

	await new Promise<void>((resolve) => server.listen(port, resolve));

	const addr = server.address();
	const actualPort = typeof addr === "object" && addr ? addr.port : port;
	const baseUrl = `http://localhost:${actualPort}`;

	// Initialize world-local for development
	try {
		process.env.PORT = String(actualPort);
		process.env.WORKFLOW_LOCAL_BASE_URL = baseUrl;
		const { createLocalWorld } = await import("@workflow/world-local");
		const { setWorld } = await import("workflow/runtime");
		const world = await createLocalWorld();
		setWorld(world);
	} catch {
		// world-local may not be installed — that's fine for production
	}

	console.log(`[c4c] Workflow server listening on ${baseUrl}`);
	console.log(`[c4c] Endpoints:`);
	console.log(`  POST ${baseUrl}/.well-known/workflow/v1/flow`);
	console.log(`  POST ${baseUrl}/.well-known/workflow/v1/step`);
	console.log(`  POST ${baseUrl}/.well-known/workflow/v1/webhook/:token`);
	console.log(`  GET  ${baseUrl}/health`);

	return {
		server,
		baseUrl,
		port: actualPort,
		close: () => new Promise<void>((r) => server.close(() => r())),
	};
}

function findHandler(dir: string, name: string): string | null {
	for (const ext of [".mjs", ".cjs", ".js"]) {
		const path = join(dir, `${name}${ext}`);
		if (existsSync(path)) return path;
	}
	return null;
}

async function loadHandler(path: string): Promise<{ POST: (req: Request) => Response | Promise<Response> }> {
	if (path.endsWith(".cjs")) {
		const require = createRequire(import.meta.url);
		return require(path);
	}
	return await import(path);
}
