/**
 * HTTP endpoints for Workflow DevKit
 *
 * Provides REST API routes for starting workflows, monitoring runs,
 * and handling webhooks. Built on the three-endpoint architecture
 * from useworkflow.dev:
 *
 * - POST /.well-known/workflow/v1/flow   (workflow execution)
 * - POST /.well-known/workflow/v1/step   (step execution)
 * - POST /.well-known/workflow/v1/webhook/:token (webhook delivery)
 *
 * Plus c4c extensions for monitoring and management.
 */

import { Hono } from "hono";
import { streamSSE } from "hono/streaming";
import {
	subscribeToRun,
	subscribeToAll,
	getExecutionStore,
	type WorkflowEvent as WorkflowEventType,
} from "@c4c/workflow";

export interface WorkflowRouterOptions {
	/**
	 * Optional: Pre-built workflow handler modules.
	 * If provided, these are wired up to the .well-known endpoints.
	 *
	 * These are generated by `workflow build` or the framework integration.
	 */
	flowHandler?: { POST: (req: Request) => Response | Promise<Response> };
	stepHandler?: { POST: (req: Request) => Response | Promise<Response> };
	webhookHandler?: { POST: (req: Request) => Response | Promise<Response> };
}

/**
 * Create an HTTP router for workflow operations.
 *
 * ## Three-Endpoint Architecture (from useworkflow.dev)
 *
 * When `flowHandler`, `stepHandler`, and `webhookHandler` are provided
 * (generated by `workflow build`), the router exposes the standard
 * .well-known/workflow/v1/ endpoints that the Workflow DevKit orchestrator
 * calls to execute workflows and steps.
 *
 * ## c4c Extensions
 *
 * Additional endpoints for monitoring:
 * - GET /workflow/runs - List run history
 * - GET /workflow/runs/:runId - Get specific run
 * - GET /workflow/runs/:runId/stream - SSE stream for run events
 * - GET /workflow/runs-stream - SSE stream for all events
 */
export function createWorkflowRouter(
	options: WorkflowRouterOptions = {},
) {
	const router = new Hono();

	// ============================================================
	// Standard Workflow DevKit endpoints (.well-known/workflow/v1/)
	// These are called by the Workflow DevKit orchestrator
	// ============================================================

	if (options.flowHandler) {
		router.post("/.well-known/workflow/v1/flow", async (c) => {
			const response = await options.flowHandler!.POST(c.req.raw);
			return response;
		});
	}

	if (options.stepHandler) {
		router.post("/.well-known/workflow/v1/step", async (c) => {
			const response = await options.stepHandler!.POST(c.req.raw);
			return response;
		});
	}

	if (options.webhookHandler) {
		router.post("/.well-known/workflow/v1/webhook/:token", async (c) => {
			const response = await options.webhookHandler!.POST(c.req.raw);
			return response;
		});
	}

	// ============================================================
	// c4c Monitoring Extensions
	// ============================================================

	/**
	 * GET /workflow/runs - List workflow run history
	 */
	router.get("/workflow/runs", (c) => {
		const store = getExecutionStore();
		const runs = store.getAllRuns();
		const stats = store.getStats();
		return c.json({ runs, stats });
	});

	/**
	 * GET /workflow/runs/:runId - Get a specific run
	 */
	router.get("/workflow/runs/:runId", (c) => {
		const runId = c.req.param("runId");
		const store = getExecutionStore();
		const run = store.getRun(runId);

		if (!run) {
			return c.json({ error: `Run '${runId}' not found` }, 404);
		}

		return c.json({ run });
	});

	/**
	 * GET /workflow/runs/:runId/stream - SSE stream for a workflow run
	 */
	router.get("/workflow/runs/:runId/stream", async (c) => {
		const runId = c.req.param("runId");
		if (!runId) {
			return c.json({ error: "runId is required" }, 400);
		}

		return streamSSE(c, async (stream) => {
			let open = true;
			const cleanup = () => {
				if (!open) return;
				open = false;
				unsubscribe();
			};

			const unsubscribe = subscribeToRun(runId, (event: WorkflowEventType) => {
				stream.writeSSE({
					event: event.type,
					data: JSON.stringify(event),
					id: String(Date.now()),
				});

				if (
					event.type === "workflow.completed" ||
					event.type === "workflow.failed"
				) {
					cleanup();
					stream.close();
				}
			});

			stream.onAbort(() => {
				cleanup();
			});

			await stream.writeSSE({
				event: "connected",
				data: JSON.stringify({ runId, timestamp: Date.now() }),
			});

			while (open) {
				await stream.sleep(15000);
				if (!open) break;
				await stream.writeSSE({
					event: "heartbeat",
					data: JSON.stringify({ runId, timestamp: Date.now() }),
				});
			}
		});
	});

	/**
	 * GET /workflow/runs-stream - SSE stream for all workflow events
	 */
	router.get("/workflow/runs-stream", async (c) => {
		return streamSSE(c, async (stream) => {
			let open = true;

			const store = getExecutionStore();

			await stream.writeSSE({
				event: "initial",
				data: JSON.stringify({
					runs: store.getAllRuns(),
					stats: store.getStats(),
					timestamp: Date.now(),
				}),
			});

			const unsubscribe = subscribeToAll((event: WorkflowEventType) => {
				if (!open) return;
				stream.writeSSE({
					event: event.type,
					data: JSON.stringify(event),
					id: String(Date.now()),
				});
			});

			stream.onAbort(() => {
				open = false;
				unsubscribe();
			});

			while (open) {
				await stream.sleep(15000);
				if (!open) break;
				await stream.writeSSE({
					event: "heartbeat",
					data: JSON.stringify({ timestamp: Date.now() }),
				});
			}
		});
	});

	return router;
}
