# Railway.app configuration
# Deploy with: railway up

[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm --filter @tsdev/core build && pnpm --filter @tsdev/adapters build"

[deploy]
startCommand = "node --import tsx/esm src/apps/http.ts"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[[services]]
name = "api"

[services.env]
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "info"
