// This file is auto-generated by c4c integrate command
// Do not edit manually.

export { TasksTriggerCreatedProcedure } from './tasks-trigger-created.gen.js';
export { TasksTriggerUpdatedProcedure } from './tasks-trigger-updated.gen.js';

import type { Procedure } from "@c4c/core";
import { TasksTriggerCreatedProcedure } from './tasks-trigger-created.gen.js';
import { TasksTriggerUpdatedProcedure } from './tasks-trigger-updated.gen.js';

export const TaskManagerTriggers: Procedure[] = [
  TasksTriggerCreatedProcedure,
  TasksTriggerUpdatedProcedure
];
