// This file is auto-generated by c4c integrate command
// Do not edit manually.

import type { Procedure, Contract } from "@c4c/core";
import { z } from "zod";

export const TaskManagerNotificationServiceNotificationsTriggerSentWebhookWebhookContract: Contract = {
  name: "task-manager.notification.service.notifications.trigger.sent.webhook.webhook",
  description: "Webhook trigger that fires when a notification is sent",
  input: z.object({
  success: z.boolean(),
  message: z.string().optional()
}),
  output: z.object({
  success: z.boolean(),
  message: z.string().optional()
}),
  metadata: {
    exposure: "external" as const,
    roles: ["workflow-node"],
    provider: "task-manager",
    operation: "notificationServiceNotificationsTriggerSentWebhookWebhook",
    tags: ["task-manager", "webhook"],
    type: "trigger" as const,
    trigger: {
      type: "webhook",
    },
  },
};

// Webhook triggers don't have a handler - they are registered as event receivers
export const TaskManagerNotificationServiceNotificationsTriggerSentWebhookWebhookProcedure: Procedure = {
  contract: TaskManagerNotificationServiceNotificationsTriggerSentWebhookWebhookContract,
  handler: async () => {
    throw new Error('Webhook triggers should not be called directly - they are invoked by the workflow engine');
  },
};
