// This file is auto-generated by c4c integrate command
// Do not edit manually.

import type { Procedure, Contract } from "@c4c/core";
import { z } from "zod";

export const TaskManagerTasksTriggerUpdatedWebhookContract: Contract = {
  name: "task-manager.tasks.trigger.updated.webhook",
  description: "Webhook fired when a task is updated",
  input: z.unknown(),
  output: z.string(),
  metadata: {
    exposure: "external" as const,
    roles: ["workflow-node"],
    provider: "task-manager",
    operation: "tasksTriggerUpdatedWebhook",
    tags: ["task-manager", "webhook"],
    type: "trigger" as const,
    trigger: {
      type: "webhook",
    },
  },
};

// Webhook triggers don't have a handler - they are registered as event receivers
export const TaskManagerTasksTriggerUpdatedWebhookProcedure: Procedure = {
  contract: TaskManagerTasksTriggerUpdatedWebhookContract,
  handler: async () => {
    throw new Error('Webhook triggers should not be called directly - they are invoked by the workflow engine');
  },
};
